from django.urls import path
from . import views
from django.conf import settings

urlpatterns = [
	path('', views.home, name='home'),
	path('main/', views.main, name='main'),
	path('cursos/', views.cursos, name='cursos'),
	path('cursos/busqueda/<str:tema>', views.search, name='search'),
	#Temas de recurso de aprendizaje
	path('cursos/clases/', views.clases, name='clases'),
	path('cursos/clases/pizarron-de-cristal/', views.pizarron_de_cristal, name='pizarron_de_cristal'),
	path('cursos/clases/pizarron-de-cristal/dimensiones-estructura-costo/', views.pizarron_de_cristal_01, name='pizarron_de_cristal_01'),
	path('cursos/clases/pizarron-de-cristal/estudio/', views.pizarron_de_cristal_02, name='pizarron_de_cristal_02'),
	path('cursos/clases/pizarron-de-cristal/plumones/', views.pizarron_de_cristal_03, name='pizarron_de_cristal_03'),
	path('cursos/clases/pizarron-de-cristal/linea-de-leds/', views.pizarron_de_cristal_04, name='pizarron_de_cristal_04'),
	path('cursos/clases/pizarron-de-cristal/grabacion-de-audio/', views.pizarron_de_cristal_05, name='pizarron_de_cristal_05'),
	path('cursos/clases/pizarron-de-cristal/cortinas/', views.pizarron_de_cristal_06, name='pizarron_de_cristal_06'),
	path('cursos/clases/pizarron-de-cristal/camaras/', views.pizarron_de_cristal_07, name='pizarron_de_cristal_07'),
	path('cursos/clases/pizarron-de-cristal/como-filmar/', views.pizarron_de_cristal_08, name='pizarron_de_cristal_08'),
	path('cursos/clases/pizarron-de-cristal/limpieza/', views.pizarron_de_cristal_09, name='pizarron_de_cristal_09'),
	path('cursos/clases/pizarron-de-cristal/contraste-correcion-de-color/', views.pizarron_de_cristal_10, name='pizarron_de_cristal_10'),
	path('cursos/clases/pizarron-de-cristal/flip/', views.pizarron_de_cristal_11, name='pizarron_de_cristal_11'),
	path('cursos/clases/pizarron-de-cristal/unir-videos/', views.pizarron_de_cristal_12, name='pizarron_de_cristal_12'),
	path('cursos/clases/pizarron-de-cristal/videos-linea-de-tiempo/', views.pizarron_de_cristal_13, name='pizarron_de_cristal_13'),
	path('cursos/clases/pizarron-de-cristal/sincronizar-audio-video/', views.pizarron_de_cristal_14, name='pizarron_de_cristal_14'),
	path('cursos/clases/pizarron-de-cristal/zoom-de-pantalla/', views.pizarron_de_cristal_15, name='pizarron_de_cristal_15'),
	path('cursos/clases/pizarron-de-cristal/resaltar-blinkear-el-video/', views.pizarron_de_cristal_16, name='pizarron_de_cristal_16'),
	path('cursos/clases/pizarron-de-cristal/clase-logica-int/', views.pizarron_de_cristal_17, name='pizarron_de_cristal_17'),
	path('cursos/clases/pizarron-de-cristal/clase-logica-char/', views.pizarron_de_cristal_18, name='pizarron_de_cristal_18'),
	path('cursos/clases/pizarron/', views.pizarron, name='pizarron'),
	path('cursos/clases/pizarron/pizarron_pequeño/', views.pizarron_pequeño, name='pizarron_pequeño'),
	path('cursos/clases/pizarron/pizarron_mediano/', views.pizarron_mediano, name='pizarron_mediano'),
	path('cursos/clases/pizarron/pizarron_grande/', views.pizarron_grande, name='pizarron_grande'),
	path('cursos/clases/pizarron/edicion_final/', views.pizarron_edicion_final, name='pizarron_edicion_final'),
	path('cursos/clases/pizarron/clase', views.pizarron_clase, name='pizarron_clase'),
	path('cursos/clases/cuaderno/', views.cuaderno, name='cuaderno'),
	path('cursos/clases/cuaderno/entorno_de_grabacion/', views.entorno_de_grabacion, name='entorno_de_grabacion'),
	path('cursos/clases/cuaderno/clase/', views.cuaderno_clase, name='cuaderno_clase'),
	path('cursos/clases/captura_de_pantalla/', views.captura_de_pantalla, name='captura_de_pantalla'),
	path('cursos/clases/captura_de_pantalla/material_de_estudios/', views.material_de_estudios, name='material_de_estudios'),
	path('cursos/clases/captura_de_pantalla/grabacion_en_SMRecorder/', views.grabacion_en_SMRecorder, name='grabacion_en_SMRecorder'),
	path('cursos/clases/captura_de_pantalla/clase_final/', views.captura_clase_final, name='captura_clase_final'),
	path('cursos/clases/presentacion_estatica/', views.presentacion_estatica, name='presentacion_estatica'),
	path('cursos/clases/presentacion_estatica/lista_de_aplicaciones/', views.lista_de_aplicaciones, name='lista_de_aplicaciones'),
	path('cursos/clases/multipantalla/', views.multipantalla, name='multipantalla'),
	path('cursos/clases/multipantalla/dimensiones_estructura_costo/', views.dimensiones_estructura_costo, name='dimensiones_estructura_costo'),
	path('cursos/clases/multipantalla/estudio/', views.estudio, name='estudio'),
	path('cursos/clases/multipantalla/plumones/', views.plumones, name='plumones'),
	path('cursos/clases/aula/', views.aula, name='aula'),
	path('cursos/clases/aula/dispositivos_y_camara/', views.dispositivos_y_camara, name='dispositivos_y_camara'),
	path('cursos/clases/aula/camara_y_material_de_apoyo/', views.camara_y_material_de_apoyo, name='camara_y_material_de_apoyo'),
	path('cursos/clases/aula/edicion_final/', views.aula_edicion_final, name='aula_edicion_final'),
	path('cursos/imagenes/', views.imagenes, name='imagen'),
	path('cursos/imagenes/esquema-de-color/', views.imagen_01, name='imagen_01'),
	path('cursos/imagenes/formatos/', views.imagen_02, name='imagen_02'),
	path('cursos/imagenes/download/pdf/', views.download_imagen, name='download_imagen'),
	path('cursos/foros-y-chats/', views.forosychats, name='forosychats'),
	path('cursos/foros-y-chats/chats/', views.chats, name='chats'),
	path('cursos/foros-y-chats/chats/chat-de-pure/', views.chat_depure, name='chat_de_pure'),
	path('cursos/foros-y-chats/chats/administrador/', views.chat_administrador, name='chat_administrador'),
	path('cursos/foros-y-chats/chats/cliente/', views.chat_cliente, name='chat_cliente'),
	path('cursos/videoconferencias/', views.videoconferencias, name='videoconferencias'),
	path('cursos/videoconferencias/definicion-del-material/', views.videoconferencias_01, name='videoconferencias_01'),
	path('cursos/videoconferencias/appear-in/', views.videoconferencias_02, name='videoconferencias_02'),
	path('cursos/videoconferencias/hang-out/', views.videoconferencias_03, name='videoconferencias_03'),
] 