# Generated by Django 2.0.13 on 2019-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='imagen',
            field=models.CharField(default='assets/img/attach-blue.png', max_length=200),
        ),
    ]
