# Generated by Django 2.0.13 on 2019-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pages_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='urlname',
            field=models.CharField(default='home', max_length=200),
        ),
    ]
